# Generated by Django 5.1.3 on 2026-07-13 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_mensagem_autor_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('curtida', 'Curtida'), ('aplauso', 'Aplauso'), ('amei', 'Amei'), ('ideia', 'Ideia')], default='curtida', max_length=20)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('mensagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacoes', to='home.mensagem')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criada_em'],
                'unique_together': {('mensagem', 'usuario')},
            },
        ),
    ]
